#!/bin/bash
if [ -f "/etc/debian_version" ]; then
    install_for_rc(){
        echo "Installing for RC"   
    }

    instal_for_pc(){
        echo "Installing for PC"   
    }

    DIALOG_TITLE="Workstation: Robot OS Installation"
    DIALOG_LISTS=("Remote Control" "Smart remote control" 1 \
        "Desktop" "Any 64bit PC or laptop" 2
    )
    DIALOG_TEXT="\nSelect workstation GUI:."
    SELECTED=$(dialog --keep-tite --title "${DIALOG_TITLE}" \
                    --radiolist "${DIALOG_TEXT}" 12 60 10 "${DIALOG_LISTS[@]}" \
                    2>&1 >/dev/tty)

    if [[ $SELECTED ==  "Models" ]] 
    then
        install_for_rc
    elif [[ $SELECTED ==  "Station" ]] 
    then
        instal_for_pc
    fi
else
    echo "Looks like you are not running a debian system."
fi
